# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "自動車運送業向けサービス"
  pageRef = "service"
  weight = 20

[[main]]
  name = "外国人採用とは"
  pageRef = "employ-foreigner"
  weight = 10

[[main]]
  name = "特定技能外国人"
  parent = "自動車運送業向けサービス"
  pageRef = "ssw"
  weight = 10

[[main]]
  name = "導入の流れ"
  parent = "自動車運送業向けサービス"
  pageRef = "process"
  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "よくある質問"
  pageRef = "faq"
  weight = 30

[[main]]
  name = "無料お問い合わせ"
  pageRef = "contact"
  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "無料で資料を受け取る"
   pageRef = "サービス資料無料ダウンロード"
   weight = 10

 [[footer]]
   name = "最短1ヶ月で入社実現可能"
   pageRef = "categories"
   weight = 20
