# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "会社案内"
  pageRef = "aboutus"
  weight = 10

[[main]]
  name    = "米国本社"
  parent  = "会社案内"
  pageRef = "usoffice"
  weight  = 11

[[main]]
  name    = "中国事務所"
  parent  = "会社案内"
  pageRef = "cnoffice"
  weight  = 12
  
[[main]]
  name = "技能人材紹介"
  pageRef = "ssw"
  weight = 20

[[main]]
  name = "自動車運送業"
  parent = "技能人材紹介"
  pageRef = "transportation"
  weight = 21
  
[[main]]
  name = "宿泊・ホテル業の人材"
  parent = "技能人材紹介"
  pageRef = "hotel"
  weight = 22
  
[[main]]
  name = "飲食業の人材"
  parent = "技能人材紹介"
  pageRef = "food"
  weight = 23
  
[[main]]
  name = "建設業の人材"
  parent = "技能人材紹介"
  pageRef = "build"
  weight = 24
  
[[main]]
  name = "オフィス人材紹介"
  pageRef = "employ-foreigner"
  weight = 30

[[main]]
  name = "中国人採用のメリット"
  parent = "技能人材紹介"
  pageRef = "merits"
  weight = 31
  
[[main]]
  name = "採用開始までの流れ"
  parent = "技能人材紹介"
  pageRef = "flow"
  weight = 32
 
  
#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

[[main]]
  name = "お問い合わせ"
  pageRef = "askinfo"
  weight = 40

[[main]]
  name = "今すぐ相談"
  parent = "お問い合わせ"
  pageRef = "contact"
  weight = 41

[[main]]
  name = "よくある質問"
  parent = "お問い合わせ"
  pageRef = "faq"
  weight = 42

[[main]]
  name    = "ニュース"
  parent = "お問い合わせ"
  pageRef = "news"
  weight  = 43

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "500時間を超える徹底事前トレーニング"
   pageRef = "training"
   weight = 10

 [[footer]]
   name = "最短1ヶ月で入社実現可能"
   pageRef = "onemonth"
   weight = 20
    
[[footer]]
  name = "多彩な就労資格に幅広く対応"
  pageRef = "visakind"
  weight = 30